default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: ojala_dev

test:
  <<: *default
  database: ojala_test

production:
  <<: *default
  database: ojala_production
